version: '3.7'
services:
  bgio-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2001:2001"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres-db
    command: sh -c "./docker/wait-for-postgres.sh && yarn start:server:dev"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432

  postgres-db:
    image: postgres:13-alpine
    ports:
      - "2002:5432"
    expose:
      - "5432"
    env_file:
      - .env
