input PlayerCondition {
  userId: String
}

input GameConditions {
  userId: String
  status: GameStatusEnum
}

enum GameStatusEnum {
  COMPLETE
  PENDING
  PLAYING
  UNKNOWN
}

type Game {
  players: [Player!]!
  status: GameStatusEnum!
  currentPlayer: User
  turnNumber: Int
  result: GameResult
}
