input PlayerCondition {
  userId: String
}

input GameConditions {
  userId: String
  status: GameStatusEnum
}

enum GameStatusEnum {
  COMPLETE
  PENDING
  PLAYING
  UNKNOWN
}

enum GameOutcome {
  DRAW
  VICTORY
}

type GameResult {
  outcome: GameOutcome!
  winner: User
  loser: User
}

type Game {
  players: [Player!]!
  status: GameStatusEnum!
  currentPlayer: User
  turnNumber: Int
  result: GameResult
}
